### ISSUE TITLE
Double Chat?

### ISSUE THREAD

**Issue by CoolLord22** [BoomerBR/LegendChat#2]
Hi, I am kind of confused, but whenever we try to chat it sends 2 messages for some reason. One message is the normal one from Minecraft, and then the second one is from the plugin. Also, doing /global sends the same message twice and I am really confused why. Thanks for any help! Let me know if you need more info.
![2016-05-23_22 07 00](https://cloud.githubusercontent.com/assets/16751239/15490051/ee497b7a-2132-11e6-8d02-3e5c1f76409c.png)

**Comment by BoomerBR** [comment]
Wich plugin do you use to add these tags to the chat?

**Comment by CoolLord22** [comment]
PermissionsEx

**Comment by BoomerBR** [comment]
You are using chat manager? or any other chat plugin?

**Comment by CoolLord22** [comment]
The only things I can think of are Essentials and ChatControl

**Comment by BoomerBR** [comment]
Do you already tried to remove this plugins to see if this still happens?

**Comment by CoolLord22** [comment]
These plugins control the main aspects of the server so I guess I just won't use yours... :( sorry
